### ISSUE TITLE
File `data/locale/en/LC_MESSAGES/FFGo.mo` missing, ffgo does not start up.

### ISSUE THREAD

**Issue by dreirund** [frougon/FFGo#4]
When I run ffgo from this git-repository, I get an error about some missing translation:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ffgo/misc.py", line 244, in __init__
    self.translator = gettext.translation(
  File "/usr/lib/python3.9/gettext.py", line 592, in translation
    raise FileNotFoundError(ENOENT,
FileNotFoundError: [Errno 2] No translation file found for domain: 'FFGo'

Error: unable to initialize the translation system. Your installation is
missing the file '/usr/lib/python3.9/site-
packages/ffgo/data/locale/en/LC_MESSAGES/FFGo.mo'. If you simply cloned or
downloaded FFGo's Git repository, it is quite normal that .mo files are
missing (they must be generated from their .po sources). Please refer to
FFGo's installation guide: docs/INSTALL/INSTALL_en. It has specific
instructions that must be followed for a successful installation from the Git
repository.
```

My locale is:

`locale`:

```
LANG=C
LC_CTYPE=en_US.UTF8
LC_NUMERIC=C
LC_TIME=C
LC_COLLATE=C
LC_MONETARY=C
LC_MESSAGES=C
LC_PAPER=de_DE.UTF8
LC_NAME=C
LC_ADDRESS=C
LC_TELEPHONE=C
LC_MEASUREMENT=C
LC_IDENTIFICATION=C
LC_ALL=
```

Running the latest release, version 1.12.7 from [here](http://frougon.net/projects/FFGo/dist/1.12.7/), does not produce the error but works.

I use the [Arch Linux package from the AUR](https://aur.archlinux.org/packages/ffgo-git/).

**Comment by frougon** [comment]
Hello,

This is quite normal and explained in the error message you pasted. The `.mo` files are generated files, they just don't belong to a source code repository. As the FFGo error message told you, you should read [docs/INSTALL/INSTALL_en](https://github.com/frougon/FFGo/blob/master/docs/INSTALL/INSTALL_en), in particular section `INSTALLATION FROM THE GIT REPOSITORY`. This will give you simple steps to generate the `.mo` files and start FFGo.

Regards
