### ISSUE TITLE
`make doc` fails with `ERROR: Invalid value `None` in intersphinx_mapping['https://docs.python.org/']. Expected a two-element tuple or list.`

### ISSUE THREAD

**Issue by dreirund** [frougon/FFGo#9]
When building this (using [&nearr;&hairsp;this template](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ffgo-git) on [Artix GNU/Linux](http://artixlinux.org/) (rolling release)), `make doc` fails with `ERROR: Invalid value `None` in intersphinx_mapping['https://docs.python.org/']. Expected a two-element tuple or list.`:

`make doc`:  
```
make -C docs/README.conditional-config.source html
make[1]: Entering directory '/var/cache/makepkg/build/ffgo-git/src/ffgo/docs/README.conditional-config.source'
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v8.1.3
loading translations [en]... done
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
ERROR: Invalid value `None` in intersphinx_mapping['https://docs.python.org/']. Expected a two-element tuple or list.

Configuration error:
Invalid `intersphinx_mapping` configuration (1 error).
make[1]: *** [Makefile:55: html] Error 2
make[1]: Leaving directory '/var/cache/makepkg/build/ffgo-git/src/ffgo/docs/README.conditional-config.source'
make: *** [Makefile:23: doc] Error 2
```

Using latest (as of time of writing this) git checkout, commit hash: 68131fc, latest commit from 2024-11-23.

Isue did not happen with a previous build from commit hash f5624be with latest commit from 2023-09-17.

Regards!

**Comment by frougon** [comment]
The duplicate assignment made it a bit difficult to understand what was happening. Thanks for your report!
